name: apk-vad-asr-simulated-streaming  
  
on:  
  workflow_dispatch:  
  
concurrency:  
  group: apk-vad-asr-simulated-streaming-${{ github.ref }}  
  cancel-in-progress: true  
  
permissions:  
  contents: write  
  
jobs:  
  simulated_streaming_asr:  
    runs-on: ubuntu-latest  
    name: Build arm64-v8a APK  
    strategy:  
      fail-fast: false  
      matrix:  
        os: [ubuntu-latest]  
        total: ["1"]  
        index: ["0"]  
  
    steps:  
      - uses: actions/checkout@v4  
        with:  
          fetch-depth: 0  
  
      - name: Update version  
        shell: bash  
        run: |  
          ./new-release.sh  
          git diff .  
  
      - uses: actions/setup-java@v4  
        with:  
          distribution: 'temurin'  
          java-version: '21'  
  
      - name: ccache  
        uses: hendrikmuhs/ccache-action@v1.2  
        with:  
          key: ${{ matrix.os }}-android  
  
      - name: Display NDK HOME  
        shell: bash  
        run: |  
          echo "ANDROID_NDK_LATEST_HOME: ${ANDROID_NDK_LATEST_HOME}"  
          ls -lh ${ANDROID_NDK_LATEST_HOME}  
  
      - name: Install Python dependencies  
        shell: bash  
        run: |  
          python3 -m pip install --upgrade pip jinja2  
  
      - name: Setup build tool version variable  
        shell: bash  
        run: |  
          BUILD_TOOL_VERSION=$(ls /usr/local/lib/android/sdk/build-tools/ | tail -n 1)  
          echo "BUILD_TOOL_VERSION=$BUILD_TOOL_VERSION" >> $GITHUB_ENV  
  
      - name: Set version variable  
        shell: bash  
        run: |  
          SHERPA_ONNX_VERSION=$(grep "SHERPA_ONNX_VERSION" ./CMakeLists.txt  | cut -d " " -f 2  | cut -d '"' -f 2)  
          echo "SHERPA_ONNX_VERSION=$SHERPA_ONNX_VERSION" >> $GITHUB_ENV  
  
      - name: Generate build script  
        shell: bash  
        run: |  
          cd scripts/apk  
          ./generate-vad-asr-apk-script.py --total ${{ matrix.total }} --index ${{ matrix.index }}  
          chmod +x build-apk-vad-asr-simulate-streaming.sh  
          mv -v ./build-apk-vad-asr-simulate-streaming.sh ../..  
  
      - name: build APK  
        shell: bash  
        run: |  
          export CMAKE_CXX_COMPILER_LAUNCHER=ccache  
          export PATH="/usr/lib/ccache:/usr/local/opt/ccache/libexec:$PATH"  
          export ANDROID_NDK=$ANDROID_NDK_LATEST_HOME  
          ./build-apk-vad-asr-simulate-streaming.sh  
  
      - name: Display APK  
        shell: bash  
        run: |  
          ls -lh ./apks/  
  
      # 签名 APK  
      - uses: r0adkll/sign-android-release@v1  
        name: Sign app APK  
        with:  
          releaseDirectory: ./apks  
          signingKeyBase64: ${{ secrets.ANDROID_SIGNING_KEY }}  
          alias: ${{ secrets.ANDROID_SIGNING_KEY_ALIAS }}  
          keyStorePassword: ${{ secrets.ANDROID_SIGNING_KEY_STORE_PASSWORD }}  
        env:  
          BUILD_TOOLS_VERSION: ${{ env.BUILD_TOOL_VERSION }}  
  
      - name: Display APK after signing  
        shell: bash  
        run: |  
          ls -lh ./apks/  
  
      - name: Rename APK after signing  
        shell: bash  
        run: |  
          cd apks  
          rm -fv signingKey.jks  
          rm -fv *.apk.idsig  
          rm -fv *-aligned.apk  
  
          all_apks=$(ls -1 *-signed.apk)  
          echo "----"  
          echo $all_apks  
          echo "----"  
          for apk in ${all_apks[@]}; do  
            n=$(echo $apk | sed -e s/-signed//)  
            mv -v $apk $n  
          done  
  
          cd ..  
  
          ls -lh ./apks/  
  
      - name: Create Release and Upload APKs  
        uses: softprops/action-gh-release@v1  
        env:  
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
        with:  
          tag_name: vad-asr-simulated-streaming-${{ github.run_number }}  
          name: VAD ASR Simulated Streaming ${{ github.run_number }}  
          draft: false  
          prerelease: false  
          files: |  
            ./apks/sherpa-onnx-${{ env.SHERPA_ONNX_VERSION }}-arm64-v8a-simulated_streaming_asr-zh_en-paraformer.apk  
            ./apks/sherpa-onnx-${{ env.SHERPA_ONNX_VERSION }}-arm64-v8a-simulated_streaming_asr-zh_en_ko_ja_yue-sense_voice_2025_09_09_int8.apk
